In [1]:
import torch

/Users/haoranhuang/opt/anaconda3/envs/ml/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
t = torch.arange(0, 8).reshape(2,2,2)
print(t)
print(t.shape)
print(t.view(-1))
print(t.view(-1).shape)

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])
torch.Size([2, 2, 2])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
torch.Size([8])


In [3]:
t2 = t %2 == 0

In [4]:
print(t2)
print(t.is_contiguous())
t.view(-1)
print(t.T.is_contiguous())
print(t.stride())
print(t.T.stride())

tensor([[[ True, False],
         [ True, False]],

        [[ True, False],
         [ True, False]]])
True
False
(4, 2, 1)
(1, 2, 4)


/var/folders/0d/6r10g92s7j9ftbq6s75yb8k40000gn/T/ipykernel_80961/3368447720.py:4: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:2980.)
  print(t.T.is_contiguous())


In [5]:
torch.arange(0, 8).view(2,2,2)

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [6]:
mps = torch.device("mps")
cpu = torch.device("cpu")

In [7]:
t.get_device()

-1

In [8]:
t1 = t.to(mps)
t2 = t.to(cpu)
t1 + t2

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!

In [10]:
data = torch.tensor([0,1,2])
mask = torch.tensor([True, False, True])
masked_data1 = torch.masked_select(data, mask)
masked_data2 = data[mask]
print(f"masked_data1 is {masked_data1}")
print(f"masked_data2 is {masked_data2}")

mps_masked_data1 = torch.masked_select(data.to(mps), mask.to(cpu))
# print(f"mps_masked_data1 is {mps_masked_data1}")
# mps_masked_data2 = data.to(mps)[mask.to(mps)]
# print(f"masked_data2 is {masked_data2}")

masked_data1 is tensor([0, 2])
masked_data2 is tensor([0, 2])


In [12]:
torch.device("cudas")

RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, ort, mps, xla, lazy, vulkan, meta, hpu, privateuseone device type at start of device string: cudas

In [36]:
torch.masked_select(
    torch.arange(0, 8),
    torch.tensor([True])
)

torch.arange(0, 8).reshape(2,2,2)[True, False, True]

tensor([], size=(0, 2, 2, 2), dtype=torch.int64)